import 'package:freezed_annotation/freezed_annotation.dart';

part 'review.freezed.dart';
part 'review.g.dart';

/// The stock review sheet — every metric, its direction, and what to ask next.
///
/// Built by `build_review.py` from the exchange's filed statements, its own
/// `stock-info` endpoint, and the market scan. The founder's Investing 101
/// framework, computed for every listed company and refreshed by the same
/// pipeline as everything else.
///
/// **There is no score, and there will not be one.** The moment nine arrows
/// become a number out of ten it is a recommendation wearing arithmetic, and
/// this publisher has no licence to make one (§8). What the sheet does instead
/// is state each figure, which way it has moved in this company's own history,
/// where it sits against its sector — and then ask the reader a question. That
/// last part is not decoration: "P/E fell while earnings rose" plus "why is it
/// cheaper than its sector?" is the same information as a verdict, with the
/// judgement left where it belongs.
@freezed
abstract class CompanyReview with _$CompanyReview {
  const factory CompanyReview({
    @Default('') String ticker,
    String? generated,
    String? sector,
    @Default(<ReviewMetric>[]) List<ReviewMetric> metrics,
    ReviewPattern? pattern,

    /// A short natural-language reading of the whole pattern, generated by
    /// `build_review_reads.py` and vetted like the briefs. Absent for a
    /// company whose metrics do not yet form a pattern worth narrating.
    @Default('') String read,
    @JsonKey(name: 'read_ar') @Default('') String readAr,
  }) = _CompanyReview;

  const CompanyReview._();

  factory CompanyReview.fromJson(Map<String, dynamic> json) =>
      _$CompanyReviewFromJson(json);

  static const CompanyReview empty = CompanyReview();

  bool get isEmpty => metrics.isEmpty;

  String readFor(bool arabic) => arabic && readAr.isNotEmpty ? readAr : read;

  /// The metrics in the order the framework teaches them: what am I paying,
  /// is the business improving, what is it earning on, how is it financed.
  List<ReviewMetric> get ordered {
    const rank = <String, int>{
      'pe': 0, 'pb': 1, 'dividend_yield': 2,
      'profit': 3, 'eps': 4, 'assets': 5, 'cash_conversion': 6,
      'roe': 7, 'roa': 8,
      'debt_equity': 9,
    };
    return [...metrics]
      ..sort((a, b) => (rank[a.key] ?? 99).compareTo(rank[b.key] ?? 99));
  }
}

/// Which way a metric has moved against this company's own history.
///
/// [unknown] is a real answer and is shown as one: a single published figure
/// with no series behind it has no direction, and drawing a flat arrow would
/// claim a stability nobody measured.
enum ReviewDirection {
  rising,
  falling,
  flat,
  unknown;

  static ReviewDirection of(String raw) => switch (raw) {
    'rising' => ReviewDirection.rising,
    'falling' => ReviewDirection.falling,
    'flat' => ReviewDirection.flat,
    _ => ReviewDirection.unknown,
  };

  bool get isKnown => this != ReviewDirection.unknown;
}

@freezed
abstract class ReviewMetric with _$ReviewMetric {
  const factory ReviewMetric({
    @Default('') String key,
    @Default(0) double value,

    /// `ratio`, `percent`, `egp_m` or `egp` — how to print [value].
    @Default('ratio') String unit,
    @Default('unknown') String direction,

    /// How many reported periods the direction was read from. Shown, because a
    /// direction off three periods is a weaker claim than one off nine and the
    /// reader is entitled to know which they have.
    @Default(0) int points,

    /// The last ten readings, oldest first — each with the period it belongs
    /// to. Tapping the row draws this as the graph that proves the direction,
    /// with the figure printed at every point.
    ///
    /// Read through a converter that tolerates a bare number as well as a
    /// `{p, v}` object, so a build that meets a document published before the
    /// period labels existed shows an unlabelled graph rather than blanking
    /// the whole sheet on a parse error.
    @JsonKey(fromJson: reviewPointsFromJson)
    @Default(<ReviewPoint>[]) List<ReviewPoint> series,

    /// A pointer at the row a reader should read next — "profit is rising but
    /// cash conversion is falling, so ask how much of it was collected". Never
    /// a verdict; it is the framework's own combine-the-signals logic, read
    /// off the sibling metrics. Absent when nothing worth pointing at moved.
    String? cause,

    /// `above` or `below` the sector median — absent when the sector has fewer
    /// than five companies carrying this metric, because a median of four is
    /// not a benchmark.
    String? peer,
    @JsonKey(name: 'peer_median') double? peerMedian,
  }) = _ReviewMetric;

  const ReviewMetric._();

  factory ReviewMetric.fromJson(Map<String, dynamic> json) =>
      _$ReviewMetricFromJson(json);

  ReviewDirection get way => ReviewDirection.of(direction);

  /// The bare values, oldest first, for a sparkline that wants only the shape.
  List<double> get values => [for (final p in series) p.value];

  bool get isAbovePeers => peer == 'above';

  bool get hasPeers => peer != null && peerMedian != null;
}

/// Series elements, from either the current `{p, v}` shape or the bare-number
/// shape an older builder published.
List<ReviewPoint> reviewPointsFromJson(List<dynamic>? raw) => [
  for (final e in raw ?? const [])
    if (e is Map<String, dynamic>)
      ReviewPoint.fromJson(e)
    else if (e is num)
      ReviewPoint(value: e.toDouble()),
];

/// One reading on the graph: the period, and the figure that period produced.
@freezed
abstract class ReviewPoint with _$ReviewPoint {
  const factory ReviewPoint({
    @JsonKey(name: 'p') @Default('') String period,
    @JsonKey(name: 'v') @Default(0) double value,
  }) = _ReviewPoint;

  factory ReviewPoint.fromJson(Map<String, dynamic> json) =>
      _$ReviewPointFromJson(json);
}

/// Where the numbers agree, and where they contradict each other.
///
/// The whole argument of the sheet: no single figure says anything, and the
/// story appears when several move together — or when one refuses to. Counts
/// and names only. A company with six metrics improving and one deteriorating
/// is described exactly that way, never summed.
@freezed
abstract class ReviewPattern with _$ReviewPattern {
  const factory ReviewPattern({
    /// How many metrics had a direction that could be read at all.
    @Default(0) int readable,
    @Default(<String>[]) List<String> improving,
    @Default(<String>[]) List<String> deteriorating,
  }) = _ReviewPattern;

  const ReviewPattern._();

  factory ReviewPattern.fromJson(Map<String, dynamic> json) =>
      _$ReviewPatternFromJson(json);

  /// True when everything readable moved the same way — the case the framework
  /// calls out, in either direction.
  bool get agrees => improving.isEmpty || deteriorating.isEmpty;
}
