// Project downloaded half-hour bars into dated execution-price observations.
// Prices at clock times mean the first trade in that half-hour bar, not a
// guaranteed fill at precisely HH:MM:00. Never interpolate missing observations.
import fs from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const directory=new URL('data-source/intraday-research/',root);
const files=(await fs.readdir(directory)).filter(n=>/-30-\d+\.json$/.test(n)).sort();
const dates=new Intl.DateTimeFormat('sv-SE',{timeZone:'Africa/Cairo',dateStyle:'short',timeStyle:'short'});
const today=dates.format(new Date()).slice(0,10);
const stocks={};
const clockTimes=['10:00','12:00','close','11:00','10:30','11:30','12:30','13:00','13:30','14:00'];
for(const file of files) {
  const raw=JSON.parse(await fs.readFile(new URL(file,directory),'utf8'));
  if(raw.status!=='complete'||raw.metadata?.timezone!=='Africa/Cairo'||!raw.bars.length)continue;
  const days=new Map();
  for(const bar of raw.bars){
    const stamp=dates.format(new Date(bar[0]*1000)), day=stamp.slice(0,10), time=stamp.slice(11,16);
    if(day>=today||!bar.slice(1,5).every(v=>Number.isFinite(v)&&v>0)||bar[2]<Math.max(bar[1],bar[4])||bar[3]>Math.min(bar[1],bar[4]))continue;
    if(!days.has(day))days.set(day,new Map());
    days.get(day).set(time,bar);
  }
  const sessions=[];
  for(const [day,bars] of [...days].sort()){
    // A truncated first day has no opening bar; do not treat it as a session.
    if(!bars.has('10:00'))continue;
    const last=[...bars].sort().at(-1)[1];
    sessions.push([day,...clockTimes.map(time=>time==='close'?last[4]:(bars.get(time)?.[1]??null))]);
  }
  stocks[raw.ticker]={source:raw.source,fetchedAt:raw.fetchedAt,timezone:'Africa/Cairo',currency:raw.metadata.currency_code,adjustment:raw.adjustment,intervalMinutes:30,priceMeaning:'first trade in the labelled 30-minute bar; close is last available bar close',sessions};
}
// A research input, not a served asset: the site reads the per-company
// documents that scripts/build_simulator_series.mjs writes from this.
const target=new URL('data-source/simulator/intraday.js',root);
await fs.writeFile(target,'// Generated by scripts/build_simulator_intraday.mjs. Do not hand-edit.\nexport const INTRADAY_STOCKS = '+JSON.stringify(stocks)+';\n');
console.log(JSON.stringify({stocks:Object.keys(stocks).length,sessions:Object.values(stocks).reduce((n,s)=>n+s.sessions.length,0),btfh:stocks.BTFH?{sessions:stocks.BTFH.sessions.length,first:stocks.BTFH.sessions[0],last:stocks.BTFH.sessions.at(-1)}:null}));
